### 3.5.2. Llama3 학습 파라미터 설정
#model_name: "meta-llama/Llama-3.2-1B-Instruct"
model_name: "meta-llama/Llama-3.2-1B-Instruct"
dataset_path: "." # './'으로 시작하면 현재 경로라는 뜻임.
question_key: "instruction"
answer_key: "output" 
max_seq_length: 512
output_dir: "./llama-3.1-korean-8b-hf-20-epoch"
report_to: "wandb"
learning_rate: 0.00005
lr_scheduler_type: "linear"
num_train_epochs: 2
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
gradient_accumulation_steps: 4
optim: "adamw_torch_fused"
save_strategy: "epoch"
weight_decay: 0.01
max_grad_norm: 0.5
warmup_ratio: 0.03
bf16: true
tf32: true
gradient_checkpointing: true
activation_checkpointing: true  ####################### 이거 내가 추가했음 
evaluation_strategy: "steps" ###################
logging_steps: 10
save_steps: 100

fsdp: "full_shard auto_wrap"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
fsdp_config:
  backward_prefetch: "backward_pre"
  forward_prefetch: "false"
  use_orig_params: "false"

