seed: 42
model_name: "google/gemma-2-9b-it" 
max_seq_length: 512
output_dir: "./model_output"
report_to: "wandb"
lr_scheduler_type: "constant"
num_train_epochs: 1
per_device_train_batch_size: 6
per_device_eval_batch_size: 8
gradient_accumulation_steps: 4
optim: "adamw_torch_fused"
save_strategy: "epoch"
weight_decay: 0.01
max_grad_norm: 0.5
warmup_ratio: 0.03
bf16: true
tf32: true
gradient_checkpointing: true
activation_checkpointing: true  ####################### 이거 내가 추가했음 
logging_steps: 15
eval_strategy: "steps"
eval_steps: 15
save_steps : 20
learning_rate: 0.0002 # 2e-4로 하니까 안 되네. 
fsdp: "full_shard auto_wrap"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
fsdp_config:
  backward_prefetch: "backward_pre"
  forward_prefetch: "false"
  use_orig_params: "false"